version: build{build}
image: Visual Studio 2017

environment:
  matrix:
    - platform: x86
      configuration: Debug
      OPENSSLDIR: C:\OpenSSL-v11-Win32
    - platform: x64
      configuration: Debug
      OPENSSL64DIR: C:\OpenSSL-v11-Win64
    - platform: x86
      configuration: Release
      OPENSSLDIR: C:\OpenSSL-v11-Win32
    - platform: x64
      configuration: Release
      OPENSSL64DIR: C:\OpenSSL-v11-Win64
matrix:
  allow_failures:
    # For some reason linking picoquicdemo.lib fails with
    # cifra.lib(chash.obj) : error LNK2001: unresolved external symbol __CheckForDebuggerJustMyCode [C:\projects\picoquic\picoquicfirst\picoquicfirst.vcxproj]
    - platform: x64
      configuration: Debug
      OPENSSL64DIR: C:\OpenSSL-v11-Win64

install:
  - ps: cmd -c "git submodule update --init --recursive 2>gitupdate.txt; exit"
    # Hopefully this is enough to install the dependencies.

build:
  parallel: true
  project: picotlsvs\picotlsvs.sln

